<?php
$meta_title = "Expert Logo Design Company for Eye-Catching Branding";
$meta_description = "Get a professional logo that reflects your brand identity. We design unique, high-quality logos with a creative approach to help your business grow.";
$keyword = 'Logo Design Company ';
$canonical = "https://logicworks.ae/logo-design-company";
$faq_data = '
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "What logo design services do you offer?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Our logo design agency produces distinctive logos alongside brand identity designs and conducts logo redesign projects. Our team delivers both digital and business logo designs for every industry through its services."
      }
    },
    {
      "@type": "Question",
      "name": "How long does the logo design process take?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Project time depends on complexity. Usually, logo designs take 1-2 weeks with revisions."
      }
    },
    {
      "@type": "Question",
      "name": "What makes a great logo?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "A remarkable logo maintains three essential traits: minimalism, distinctiveness and persistent memorability. A logo should match your brand’s values and work on multiple platforms."
      }
    },
    {
      "@type": "Question",
      "name": "Can I request revisions to my logo?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Our company allows unlimited revision cycles to achieve complete client satisfaction. Our team collaborates directly with you to adjust your design until it matches your vision."
      }
    },
    {
      "@type": "Question",
      "name": "How Our Logo Designs Shape Industry Trends",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "We stay updated with the latest design trends. Our team blends creativity with market insights. We ensure each logo feels modern and relevant. Strong branding helps businesses grow and stand out. We use timeless design elements for lasting appeal. Our process includes research and innovation. We create logos that influence industry standards. Your brand stays ahead with our strategic approach"
      }
    },
    {
      "@type": "Question",
      "name": "How We Create Logos That Capture Your Vision",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "We start by understanding your brand values. Our team listens to your ideas carefully. Based on your input, we sketch multiple concepts. Every design reflects your business identity. We refine and improve based on feedback. Colors, fonts, and symbols are chosen wisely. The final logo aligns perfectly with your vision. Your brand gets a unique and meaningful identity."
      }
    },
    {
      "@type": "Question",
      "name": "The Impact of Strong Logo Design on Brands",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "An excellent logo enables consumers to instantly recognize brand identity. The company establishes trust bonds with customers and gains their credibility. An effective brand naming system helps businesses draw in more possible clients. When logos are strategically designed, they create brand distinctiveness in the market. The logo produces enduring visual effects for audience members. A unique design strengthens brand loyalty over time. Investing in a strong logo leads to business growth."
      }
    },
    {
      "@type": "Question",
      "name": "How Our Process Delivers Unique Brand Identities",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "We research your industry and competitors first. This helps us create a strong brand identity. Our designs are customized to match your business. We refine every detail for maximum impact. The goal is to make your brand memorable. We ensure your logo works across all platforms. Every step focuses on creativity and strategy. Your logo will be both modern and timeless"
      }
    },
    {
      "@type": "Question",
      "name": "Why Our Logo Design Approach Stands Above Others",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "We prioritize originality in every design. Our logo design agency focuses on quality over quantity. Every logo is crafted with purpose and precision. We involve clients in every step. Our style is a combination of creativity and strategy. Details are taken care of in order to have a perfect final design. We polish till you are fully contented. Your brand gets a professional and impactful logo."
      }
    }
  ]
}
</script>
<!--FAQPage Code Generated by https://saijogeorge.com/json-ld-schema-generator/faq/-->
';
include("includes/head.php");
include("includes/header.php");
?>

<main class="logo-design-company-page bg-black">
    <!-- Hero section -->
    <section class="consultancy-hero-sec section-bg">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-8">
                    <h1 class="text-white">Expert <span>Logo Design Company</span> for Eye-Catching Branding</h1>
                    <p class="text-white">Logo Design Company focused on clean, modern, and effective logo solutions.
                    </p>
                    <div class="seo-btn">
                       <a href="https://wa.me/971529502258" target="_blank" class="live-chats">Live Chat</a>
                        <a href="#" id="openPopup">Get A Quote</a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <img src="assests/images/logo-design-company/banner-image.webp" alt="logo-design-banner-img">
                </div>
            </div>
        </div>
    </section>

    <section class="section-marquee section-bg">
        <div class="container" style="max-width: 100%; padding: 0px;">
            <div class="row marwuee-row">
                <div class="col" style="padding: 0px;">
                    <div class="marquee">
                        <div class="marquee__row">
                            <div class="marquee__item">
                                <p class="marquee__text">LOGO DESIGN COMPANY&nbsp;—&nbsp;LOGO DESIGN COMPANY</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/service/Star.webp"></span>
                            <div class="marquee__item">
                                <p class="marquee__text">LOGO DESIGN COMPANY</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/service/Star.webp"></span>
                            <div class="marquee__item">
                                <p class="marquee__text">LOGO DESIGN COMPANY</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/service/Star.webp"></span>
                        </div>
                        <div aria-hidden="true" class="marquee__row">
                            <div class="marquee__item">
                                <p class="marquee__text">LOGO DESIGN COMPANY&nbsp;—&nbsp;LOGO DESIGN COMPANY</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/service/Star.webp"></span>
                            <div class="marquee__item">
                                <p class="marquee__text">LOGO DESIGN COMPANY</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/service/Star.webp"></span>
                            <div class="marquee__item">
                                <p class="marquee__text">LOGO DESIGN COMPANY</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/service/Star.webp"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="branding-main-sec section-bg pt-b-80" id="logo-company-sec"
        style="background-image:url(assests/images/logo-design-company/bg-pattern.webp);">
        <div class="container" style="display: block;">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center text-white same-all">ABOUT US</h2>
                    <!-- <h4 class="text-center text-white">Who We Are</h4> -->
                    <p class="text-center text-white app-txt">We are a logo design company creating unique brand
                        identities. Our team creates logos with simplicity, creativity, and business growth in mind.
                        These logos capture and reflect your brand’s vision clearly.</p>
                </div>
            </div>

            <div class="row branding-row">
                <div class="col-lg-4" style="background-image: url(assests/images/logo-design-company/about-03.webp);">
                    <h3 class=" text-white">Creativity Matters</h3>
                    <p class="text-white">We create unique logos that make brands different from others.</p>
                </div>

                <div class="col-lg-4" style="background-image: url(assests/images/logo-design-company/about-02.webp);">
                    <h3 class="text-white">Customer Focus</h3>
                    <p class="text-white">We understand your requirements and design logos that match expectations.</p>
                </div>

                <div class="col-lg-4" style="background-image: url(assests/images/logo-design-company/about-01.webp);">
                    <h3 class="text-white">Quality First</h3>
                    <p class="text-white">Our logo designs are of high-quality, professional, and long-lasting.</p>
                </div>
            </div>

            <div class="row btn-brand text-center">
                <div class="col-lg-12">
                    <p class="text-white">Make Your Brand Unforgettable with a Professionally Designed Logo!</p>
                    <a href="#" class="dark-color">START NOW!</a>
                </div>
            </div>

            <div class="row align-items-center asword-serivce">
                <div class="col">
                    <h2 class="text-white text-center same-all">OUR SERVICES</h2>
                    <p class="text-white text-center app-txt">We create logos that represent your brand with clarity and
                        style.</p>
                </div>
            </div>

            <div class="row align-items-center adwords-row">
                <div class="col-lg-4">
                    <div class="adword-card"
                        style="background-color: #59249A; padding: 30px 20px; border-radius: 15px;">
                        <img src="assests/images/adword-marketing/keywords.png" class="pb-20">
                        <h4 class="text-white">Custom Logo Design</h4>
                        <p class="text-white">We create logos that match your brand’s identity. Our team designs unique
                            logos from scratch. Every design reflects your business values and style. We inculcate
                            simplicity, creativity, and professionals. A good logo makes people know your brand within a
                            short time. It begins with research, then proceeds to brainstorming and eventually concludes
                            with refinement of ideas. We collaborate with you through understanding your needs.</p>
                        <p class="text-white">The final product delivers sharp logo designs in multiple formats. The
                            company uses modern minimalist approaches to design. Your business will expand when it uses
                            high-quality logo designs. Your logo will stand apart from others because our team takes
                            responsibility for it. Your brand needs a logo that people will not forget easily.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="adword-card"
                        style="background-color: #59249A; padding: 50px 20px; border-radius: 15px;">
                        <img src="assests/images/adword-marketing/keywords-01.png" class="pb-20">
                        <h4 class="text-white">Logo Redesign</h4>
                        <p class="text-white">Is your current logo outdated or ineffective? We refresh logos while
                            keeping brand identity intact. A modern logo improves recognition and trust. We refine
                            colors, fonts, and design elements. Our team enhances your logo for better impact. Every
                            redesign focuses on clarity and simplicity. We ensure your new logo works across all
                            platforms.</p>
                        <p class="text-white">Your brand stays relevant with an updated look. A fresh logo attracts more
                            customers. We create designs that are modern and professional. Our goal is to make your logo
                            memorable. Let’s give your brand a fresh, powerful identity.</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="adword-card"
                        style="background-color: #59249A; padding: 50px 20px; border-radius: 15px;">
                        <img src="assests/images/adword-marketing/keywords-02.png" class="pb-20">
                        <h4 class="text-white">Business Branding Logo</h4>
                        <p class="text-white">A strong brand starts with a great logo. We design logos that build trust
                            and credibility. Your logo represents your business personality. Our team designs
                            professional logos which match the specifications of your particular industry. The right
                            logo design format creates lasting visual memories. We optimize your logo to function on
                            every branding platform.</p>
                        <p class="text-white">From websites to business cards, your logo stands out. A professional
                            design makes your brand look reliable. We focus on balance, color, and meaning. Every detail
                            is crafted to enhance brand identity. Your business deserves a logo that speaks for itself.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section-bg logo-compnay-portolio" style="margin-top: 120px;">
        <div class="container" style="display: block;">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <h2 class="text-white text-center same-all">PORTFOLIO</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3">
                    <div class="app-pagination">
                        <div thumbsSlider="" class="swiper success-pagination-main">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <img src="assests/images/logo-design-company/pagi-01.webp" alt="process-02">
                                        </div>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <img src="assests/images/logo-design-company/pagi-02.webp" alt="process-03">
                                        </div>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <img src="assests/images/logo-design-company/pagi-03.webp" alt="process-04">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-9">
                    <div class="device-slider-all">
                        <div class="swiper device-slider">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide">
                                    <div class="device-content text-center">
                                        <img src="assests/images/logo-design-company/slider--01.webp" alt="process-02">
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <div class="device-content text-center">
                                        <img src="assests/images/logo-design-company/slider--02.webp" alt="process-03">
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <div class="device-content text-center">
                                        <img src="assests/images/logo-design-company/slider--03.webp" alt="process-04">
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-button-next"></div>
                            <div class="swiper-button-prev"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section-bg logo-compnay-third">
        <div class="container" style="display: block; max-width: 1920px; padding: 0;">
            <div class="row blurb-row-digits" style="background-color: #59249A;">
                <div class="col-lg-3">
                    <div class="blurb-main">
                        <img src="assests/images/marketing/world.png">
                        <h3 class="text-white">Global Presence</h3>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="blurb-main">
                        <img src="assests/images/marketing/award.png">
                        <h3 class="text-white">Expert Designers</h3>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="blurb-main">
                        <img src="assests/images/marketing/unlimited.png">
                        <h3 class="text-white">Endless Revisions</h3>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="blurb-main">
                        <img src="assests/images/marketing/money.png">
                        <h3 class="text-white">Refund Guarantee</h3>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="blurb-main">
                        <img src="assests/images/marketing/fastest.png">
                        <h3 class="text-white">Quick Delivery</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section-bg dubai-app-teechnology logo-company-development pt-b-80"
        style="background-image: url(assests/images/logo-design-company/development-bg.webp);">
        <div class="container-fluid" style="display: block;">
            <div class="row align-items-center transform-row">
                <div class="col-lg-4">
                    <img src="assests/images/marketing/banda.webp" alt="logo-design-bnda">
                </div>
                <div class="col-lg-8">
                    <h2 class="text-white same-all text-end">Our Expertise Has Fueled the Growth of 8,000+ Businesses
                    </h2>
                    <div class="digital-two-btn">
                         <a href="https://wa.me/971529502258" target="_blank">Call Now</a>
                        <a href="#" id="openPopup">Get a quote</a>
                    </div>
                </div>
            </div>

            <div class="row logo-company-choose">
                <div class="col">
                    <h2 class="text-white text-center same-all">WHY CHOOSE LOGIC WORKS?</h2>
                    <!-- <p class="text-white text-center app-txt pb-30">YOUR TRUSTED PARTNER FOR EFFECTIVE ADVERTISING</p> -->

                    <div class="app-slider">
                        <div class="swiper app-slider-main">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide">
                                    <img src="assests/images/advertising-agency/slide-01.webp" alt="slide-01">
                                    <div class="app-content">
                                        <h4 class="text-white">Expert Designers</h4>
                                        <p class="text-white">Skilled designers with years of experience in logo
                                            creation.</p>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <img src="assests/images/advertising-agency/slide-02.webp" alt="slide-02">
                                    <div class="app-content">
                                        <h4 class="text-white">Custom Designs</h4>
                                        <p class="text-white">Get customized logo that represents your brand identity.
                                        </p>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <img src="assests/images/advertising-agency/slide-03.webp" alt="slide-03">
                                    <div class="app-content">
                                        <h4 class="text-white">Timeless Appeal</h4>
                                        <p class="text-white">We create designs that remain relevant over time.</p>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <img src="assests/images/advertising-agency/slide-04.webp" alt="slide-01">
                                    <div class="app-content">
                                        <h4 class="text-white">Brand-Centric Approach</h4>
                                        <p class="text-white">Logos that align with your business values and goals.
                                        </p>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <img src="assests/images/advertising-agency/slide-01.webp" alt="slide-01">
                                    <div class="app-content">
                                        <h4 class="text-white">Versatile Designs</h4>
                                        <p class="text-white">Suitable for websites, business cards, packaging, and
                                            more.</p>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <img src="assests/images/advertising-agency/slide-02.webp" alt="slide-02">
                                    <div class="app-content">
                                        <h4 class="text-white">Industry-Specific</h4>
                                        <p class="text-white">Logos designed to match your business niche and audience.
                                        </p>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <img src="assests/images/advertising-agency/slide-03.webp" alt="slide-03">
                                    <div class="app-content">
                                        <h4 class="text-white">Scalable Solutions</h4>
                                        <p class="text-white">High-quality designs that retain clarity across all
                                            platforms.</p>
                                    </div>
                                </div>
                                <div class="swiper-slide">
                                    <img src="assests/images/advertising-agency/slide-04.webp" alt="slide-01">
                                    <div class="app-content">
                                        <h4 class="text-white">Client Satisfaction</h4>
                                        <p class="text-white">We make sure the final design meets your expectations and
                                            vision.
                                        </p>
                                    </div>
                                </div>

                            </div>
                            <div class="swiper-button-next"></div>
                            <div class="swiper-button-prev"></div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row counter-sec-logo counter-sec align-items-center">
                <div class="col-lg-5">
                    <h4 class="text-white">Get Noticed</h4>
                    <h2 class="text-white">Strengthen Your Brand with a Professional Logo</h2>
                    <p class="text-white">We have completed hundreds of logo projects in different industries. Our
                        portfolio highlights creativity and innovation. It reflects the quality businesses rely on.</p>
                </div>
                <div class="col-lg-3">
                    <div class="bor-coutn">
                        <h3 class="text-white">10+</h3>
                    </div>
                </div>
                <div class="col-lg-4">
                    <h5 class="text-white text-end">10+ Years of Expertise</h5>
                    <p class="text-white text-end">We have provided high-quality logo design services for over ten
                        years. Our experience helps us stay ahead in the industry. We create designs that are both
                        impactful and timeless.
                    </p>
                </div>
            </div>

            <div class="row blurb-row">
                <div class="col">
                    <div class="blurb-mod">
                        <img src="assests/images/service/100-satisfactions-Guarantee.png" alt="img-logo-001">
                        <hr>
                        <p class="text-white">Satisfaction Guaranteed</p>
                    </div>

                    <div class="blurb-mod">
                        <img src="assests/images/service/unique-Design.png" alt="img-logo-002">
                        <hr>
                        <p class="text-white">Original Designs</p>
                    </div>

                    <div class="blurb-mod">
                        <img src="assests/images/service/100-money-back.png" alt="img-logo-003">
                        <hr>
                        <p class="text-white">Refund Assurance</p>
                    </div>

                    <div class="blurb-mod">
                        <img src="assests/images/service/Design-Consultancy.png" alt="img-logo-004">
                        <hr>
                        <p class="text-white">Round-the-Clock Support</p>
                    </div>

                    <div class="blurb-mod">
                        <img src="assests/images/service/award-winning.png" alt="img-logo-005">
                        <hr>
                        <p class="text-white">Expert Team</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php
    include("includes/clint-review.php");
    ?>
    <section class="logotab-sec section-bg pt-b-80 logo-company-process">
        <div class="container" style="display: block;">
            <div class="row">
                <div class="col">
                    <h2 class="text-white algn-centr logo-h2">Our Logo Design Process</h2>
                    <p class="text-white text-center">We follow a structured process to create the perfect logo for your
                        brand.</p>
                    <div class="unique-tab-container">
                        <button class="unique-tab-button active-tab" data-target="UniqueConsultation">Research</button>
                        <button class="unique-tab-button" data-target="UniqueConcept">Development</button>
                        <button class="unique-tab-button" data-target="UniqueRevisions">Refinement</button>
                        <button class="unique-tab-button" data-target="UniqueDelivery">Delivery</button>
                    </div>
                    <div class="tab-delivery"
                        style="background-image: url(assests/images/logo-design-company/tab-bg.png);">
                        <div class="unique-tab-container">
                            <div id="UniqueConsultation" class="unique-tab-content" style="display: block;">
                                <div class="row align-items-center">
                                    <div class="col-lg-6">
                                        <h3>In-Depth Research</h3>
                                        <p>Initially we start with learning about your brand objectives and establishing
                                            your business objectives. The team studies your market space along with
                                            industry competitors while observing your target customer base. A
                                            well-researched design makes a strong impact. We focus on colors,
                                            typography, and symbols that suit your business. Every detail is considered
                                            to ensure your logo fits your brand identity. Research helps us design with
                                            strategy, not just style. Your logo should capture attention of your
                                            audience instantly. A data-driven approach ensures lasting results. We lay
                                            the foundation for a perfect logo with proper research.
                                        </p>
                                        <!-- <ul>
                                            <li>Identify brand values</li>
                                            <li>Define target audience</li>
                                            <li>Set design objectives</li>
                                        </ul> -->
                                    </div>
                                    <div class="col-lg-6">
                                        <img src="assests/images/logo-design/tab-img.png" />
                                    </div>
                                </div>
                            </div>

                            <div id="UniqueConcept" class="unique-tab-content">
                                <div class="row align-items-center">
                                    <div class="col-lg-6">
                                        <h3>Concept Development</h3>
                                        <p>Our designers create multiple ideas based on research. We explore different
                                            styles, shapes, and color combinations. Our design concept aims to represent
                                            your brand effectively. Brainstorming allows us to test creative
                                            possibilities. We refine and adjust ideas until we find the best fit. Our
                                            designers create all logos with clarity and uniqueness. We focus on making
                                            your logo memorable and professional. This phase ensures you have strong
                                            options to choose from. Our team presents different variations for review.
                                            You get a logo concept that aligns with your brand vision.</p>

                                        <!-- <ul>
                                            <li>Analyze competitor logos</li>
                                            <li>Explore design trends</li>
                                            <li>Gather creative inspiration</li>
                                        </ul> -->
                                    </div>
                                    <div class="col-lg-6">
                                        <img src="assests/images/logo-design/tab-img-11.webp" alt="tab-img-001" />
                                    </div>
                                </div>
                            </div>

                            <div id="UniqueRevisions" class="unique-tab-content">
                                <div class="row align-items-center">
                                    <div class="col-lg-6">
                                        <h3>Design & Refinement</h3>
                                        <p>After choosing a concept, we improve it carefully. Colors, fonts, and layouts
                                            are fine-tuned. Every detail is made to strengthen your logo. Refinements
                                            ensure your logo is balanced and appealing. We refine the design based on
                                            your feedback. Our team ensures clarity and balance. Your input helps create
                                            the best version. We align the design with your brand. Every change enhances
                                            the final look. We focus on timeless and polished results. A well-crafted
                                            logo leaves a lasting impact.</p>
                                        <!-- <ul>
                                            <li>Develop design concepts</li>
                                            <li>Collaborate for feedback</li>
                                            <li>Ensure scalability</li>
                                        </ul> -->
                                    </div>
                                    <div class="col-lg-6">
                                        <img src="assests/images/logo-design/tab-img-33.webp" alt="tab-img-003" />
                                    </div>
                                </div>
                            </div>

                            <div id="UniqueDelivery" class="unique-tab-content">
                                <div class="row align-items-center">
                                    <div class="col-lg-6">
                                        <h3>Final Delivery</h3>
                                        <p>After final approval, we prepare high-quality logo files. You receive
                                            multiple formats for digital and print use. Your logo is ready for business
                                            cards or websites. High resolution keeps the logo clear. We provide color
                                            variations if needed. Your brand gets a professional, scalable design. Every
                                            file is optimized for clarity and sharpness. We ensure smooth implementation
                                            for branding materials. Your final logo is ready for success.</p>

                                        <!-- <ul>
                                            <li>Provide logo files</li>
                                            <li>Optimize for platforms</li>
                                            <li>Deliver brand guidelines</li>
                                        </ul> -->
                                    </div>
                                    <div class="col-lg-6">
                                        <img src="assests/images/logo-design/tab-img-22.webp" alt="tab-img-004" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row justify-content-space-between faq-home faq-logo-deisgn">
                <div class="col">
                <h2 class="text-white text-center"><span>FAQ</span>'S</h2>
                    <div class="faqss">
                        <div class="quwstion">
                            <button class="accordions">What logo design services do you offer?</button>
                            <div class="panel">
                                <p>Our logo design agency produces distinctive logos alongside brand identity designs
                                    and conducts logo redesign projects. Our team delivers both digital and business
                                    logo designs for every industry through its services.</p>
                            </div>
                        </div>

                        <div class="quwstion">
                            <button class="accordions">How long does the logo design process take?</button>
                            <div class="panel">
                                <p>Project time depends on complexity. Usually, logo designs take 1-2 weeks with
                                    revisions.
                                </p>
                            </div>
                        </div>

                        <div class="quwstion">
                            <button class="accordions">What makes a great logo?</button>
                            <div class="panel">
                                <p>A remarkable logo maintains three essential traits: minimalism, distinctiveness and
                                    persistent memorability. A logo should match your brand’s values and work on
                                    multiple platforms.</p>
                            </div>
                        </div>

                        <div class="quwstion">
                            <button class="accordions">Can I request revisions to my logo?</button>
                            <div class="panel">
                                <p>Our company allows unlimited revision cycles to achieve complete client satisfaction.
                                    Our team collaborates directly with you to adjust your design until it matches your
                                    vision.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


</main>

<?php
include("includes/footer.php");
?>

<style>
    .logo-design-company-page {
        overflow: hidden;
    }

    .logo-company-development {
        background-size: contain;
        background-repeat: no-repeat;
        background-position: center;
    }

    .logo-company-process {
        background-repeat: no-repeat;
        background-size: cover;
        background-position: -570px -400px;
    }

    .slider-reviews {
        flex-direction: row !important;
    }

    .slider-reviews .tesi-roww p.text-white {
        margin: 0px;
    }

    .logo-company-process .tab-delivery {
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
    }

    .faq-logo-deisgn .faqss .panel p {
        margin-top: 0px;
        margin-bottom: 0px;
    }

    .logo-company-process p.text-white.text-center {
        margin-top: 0px;
    }

    .logo-company-choose,
    .dubai-app-teechnology .counter-sec-logo.counter-sec {
        padding-top: 80px;
        max-width: 1330px;
    }

    .dubai-app-teechnology .blurb-row {
        max-width: 1330px;
    }

    .logo-company-choose h4.text-white {
        min-height: 0px !important;
    }

    .logo-compnay-third .blurb-row-digits {
        margin-top: 0px !important;
    }

    .logo-compnay-third {
        padding-top: 80px;
    }

    .logo-compnay-portolio h2.text-white.text-center.same-all {
        text-transform: uppercase;
        letter-spacing: 5px;
        text-shadow: -10px 1px 1px #515151,
            2px -2px 0px #000000,
            -2px 2px 0px #000000,
            2px 2px 0px #101010;
        padding: 20px;
    }

    #logo-company-sec .asword-serivce {
        padding-top: 80px;
    }

    #logo-company-sec h4.text-center.text-white {
        font-size: 30px;
        font-weight: 600;
    }

    #logo-company-sec .asword-serivce p.text-white.text-center.app-txt,
    #logo-company-sec p.text-center.text-white.app-txt {
        max-width: 100%;
    }

    .adwords-row .adword-card,
    .app-slider-sec .adwords-row .col-lg-4 {
        position: relative;
    }

    .adwords-row .col-lg-4:hover .adword-card:before {
        transform: rotate(6deg);
    }

    .adwords-row .col-lg-4 .adword-card:before {
        content: '';
        position: absolute;
        background-color: #fff;
        width: 100%;
        height: 100%;
        border-radius: 15px;
        left: 0%;
        top: 0;
        transform: rotate(0deg);
        z-index: -1;
        transition: 0.5s all ease-in-out;
    }

    .adword-card h4 {
        font-size: 24px;
        font-weight: 600;
    }

    .adword-card p {
        font-size: 13px;
        font-weight: 400;
        line-height: 17px;
    }

    .app-slider-sec .adwords-row .col-lg-4:hover .adword-card:before {
        transform: rotate(6deg);
    }

    .adwords-row .adword-card,
    .adwords-row .col-lg-4 {
        position: relative;
    }

    .adwords-row .col-lg-4 {
        z-index: 1;
    }

    .logo-design-company-page .marwuee-row:before {
        CONTENT: unset !IMPORTANT;
    }

    .section-marquee .marquee {
        transform: rotate(-2deg);
    }

    .logo-compnay-portolio .success-pagination-main .swiper-wrapper {
        display: block !important;
    }

    .logo-compnay-portolio .success-pagination-main .swiper-wrapper .swiper-slide {
        width: 100% !important;
    }

    .logo-compnay-portolio .success-pagination-main .swiper-wrapper .col-lg-12 img {
        width: 100%;
        max-width: 236px;
        margin: 5px;
        border-radius: 26px;
    }

    .logo-compnay-portolio .success-pagination-main .swiper-wrapper .swiper-slide-thumb-active img {
        box-shadow: 0px 0px 10px 1px #5BE3DF;
        border: 1px solid #5BE3DF;
    }

    .logo-compnay-portolio .swiper-button-prev {
        background: url(assests/images/arrow-left.webp);
        background-repeat: no-repeat;
        width: 73px;
        height: 54px;
        left: 2%;
    }

    .logo-compnay-portolio .swiper-button-prev:after,
    .logo-compnay-portolio .swiper-button-next:after {
        font-size: 0px;
    }

    .logo-compnay-portolio .swiper-button-next {
        background: url(assests/images/arrow-right.webp);
        background-repeat: no-repeat;
        width: 73px;
        height: 54px;
        right: 2%;
    }

    .device-slider-all .device-content {
        box-shadow: 0px 0px 10px 1px #5BE3DF;
        border: 1px solid #5BE3DF;
        margin: 5px;
    }

    .logo-company-choose .swiper-pagination span.swiper-pagination-bullet {
        background: #747474;
        width: 18px;
        height: 18px;
        opacity: 1;
    }

    .logo-company-choose .swiper-pagination span.swiper-pagination-bullet.swiper-pagination-bullet-active {
        box-shadow: 0px 0px 10px 4px #e40aff;
        background-color: #fff;
    }

    .logo-company-choose .swiper-button-next {
        background: url(assests/images/arrow-right.webp);
        width: 73px;
        height: 54px;
        background-repeat: no-repeat;
        top: unset;
        bottom: -1%;
        z-index: 199999;
    }

    .logo-company-choose .swiper-button-prev {
        background: url(assests/images/arrow-left.webp);
        width: 73px;
        height: 54px;
        background-repeat: no-repeat;
        top: unset;
        bottom: -1%;
        z-index: 199999;
        left: unset;
        right: 8%;
    }

    @media (max-width: 1450px) and (min-width: 1152px) {
        .logo-design-company-page .section-marquee {
            margin-top: -1px;
            margin-bottom: -1px;
        }

        .branding-main-sec {
            background-size: contain;
            margin-bottom: -1px;
        }

        .logo-compnay-portolio .success-pagination-main .swiper-wrapper .col-lg-12 img {
            max-width: 203px;
        }

        .logo-compnay-third {
            margin-top: -1px;
        }

        .logo-company-development .row.align-items-center.transform-row {
            margin-top: 0px !important;
        }

        .logo-company-choose,
        .dubai-app-teechnology .counter-sec-logo.counter-sec {
            max-width: 1260px;
        }

        .logo-company-development {
            margin-bottom: -1px;
        }

        .logo-company-process {
            background-position: -810px -20px;
            padding-top: 0px;
            margin-bottom: -1px;
        }
    }

    @media (max-width: 1026px) {
        .logo-design-company-page .section-marquee .marquee {
            transform: rotate(0deg);
        }

        .logo-design-company-page .app-txt {
            font-size: 20px;
        }

        .logo-design-company-page .adwords-row .col-lg-4:nth-child(2) {
            margin-top: 40px;
            margin-bottom: 40px;
        }

        .logo-compnay-portolio .success-pagination-main .swiper-wrapper .col-lg-12 img {
            max-width: 100%;
        }

        .logo-compnay-portolio .row .col-lg-3 {
            width: 25%;
        }

        .logo-compnay-portolio .row .col-lg-9 {
            width: 75%;
        }

        .logo-company-development .row.align-items-center.transform-row {
            margin-top: 60px !important;
        }

        .logo-company-process {
            background-size: cover;
            background-position: bottom;
        }
    }

    @media (max-width: 600px) {
        .logo-design-company-page .app-txt {
            font-size: 14px;
        }

        #logo-company-sec h4.text-center.text-white {
            font-size: 20px;
        }

        .logo-compnay-portolio h2.text-white.text-center.same-all {
            padding: 0px;
        }

        .logo-compnay-portolio .row .col-lg-9 {
            width: 100%;
        }

        .logo-compnay-portolio .row .col-lg-3 {
            width: 100%;
        }

        .logo-compnay-portolio .row {
            flex-direction: column-reverse;
        }

        .logo-compnay-portolio .success-pagination-main .swiper-wrapper .swiper-slide {
            width: 33.33% !important;
            margin-right: 0px !important;
        }

        .logo-compnay-portolio .success-pagination-main .swiper-wrapper {
            display: flex !important;
        }

        .logo-compnay-portolio {
            margin-top: -1px;
            margin-bottom: -1px;
        }

        .logo-compnay-portolio .swiper-button-next,
        .logo-compnay-portolio .swiper-button-prev {
            display: none;
        }

        .logo-compnay-third {
            padding-top: 30px;
        }

        .logo-company-choose,
        .dubai-app-teechnology .counter-sec-logo.counter-sec {
            padding-top: 40px;
            max-width: 100%;
        }

        .logo-design-company-page .counter-sec h3 {
            padding: 50px 26px;
            font-size: 90px;
            height: 230px;
            line-height: 120px;
        }

        .logo-company-process {
            margin-top: -1px;
            padding-top: 0px !important;
            margin-bottom: -1px;
        }

        .logo-company-process .row.justify-content-space-between.our-case-section {
            padding-top: 60px !important;
        }
    }
</style>

<script>
    var swiper = new Swiper(".success-pagination-main", {
        spaceBetween: 20,
        slidesPerView: 3,
        freeMode: true,
        watchSlidesProgress: true,
    });
    var swiper2 = new Swiper(".device-slider", {
        spaceBetween: 20,
        // autoplay: {
        //     delay: 2500,
        //     disableOnInteraction: false,
        // },
        loop: true,
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
        thumbs: {
            swiper: swiper,
        },
    });
</script>

<script>
    var swiper = new Swiper(".app-slider-main", {
        slidesPerView: 4,
        centeredSlides: true,
        spaceBetween: 30,
        grabCursor: true,
        // autoplay: {
        //     delay: 2500,
        //     disableOnInteraction: false,
        // },
        loop: true,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
        breakpoints: {
            320: {
                slidesPerView: 1,
                spaceBetween: 20,
            },
            600: {
                slidesPerView: 1,
                spaceBetween: 20,
            },
            768: {
                slidesPerView: 2,
                spaceBetween: 30,
            },
            1024: {
                slidesPerView: 3,
                spaceBetween: 30,
            },
            1920: {
                slidesPerView: 4,
                spaceBetween: 30,
            },
        },
    });
</script>