<?php

$meta_title = "SEO Consultancy in Dubai | Logic Works Experts";
$meta_description = "We help businesses grow online. Our SEO consultants improve rankings and traffic. Real strategies bring measurable results.";
$keyword = 'Seo Consultancy';
$canonical = "https://logicworks.ae/seo-consultancy";
$custom_schema = '
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Service",
  "@id": "https://logicworks.ae/#seo-consultancy",
  "name": "SEO Consultancy",
  "serviceType": "Search Engine Optimization (SEO)",
  "alternateName": "SEO Consultancy",
  "url": "https://logicworks.ae/seo-consultancy",
  "description": "Logic Works provides expert SEO consultancy services that improve search rankings, enhance visibility, and drive measurable business growth",
  "provider": {
    "@type": "Organization",
    "name": "Logic Works",
    "url": "https://logicworks.ae",
    "logo": "https://logicworks.ae/assests/images/head-logo.png",
    "telephone": "+971 52 950 2258",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "Al Barsha 1, Sheikh Zayed Rd",
      "addressLocality": "Dubai",
      "addressRegion": "Dubai",
      "addressCountry": "AE"
    },
    "sameAs": [
      "https://www.facebook.com/logicworks.ae",
      "https://www.instagram.com/logicworks.ae/"
    ]
  },
  "areaServed": {
    "@type": "Place",
    "name": "Dubai, UAE"
  }
}
</script>
';

$faq_data = '
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {
      "@type": "Question",
      "name": "How long does it take to see results from SEO consultancy?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "SEO results vary based on competition, website condition, and goals. Many clients begin noticing improvements in visibility within three to six months.\n Yes. We often support in-house teams by providing strategy, technical guidance, and reporting that align with their ongoing efforts."
      }
    },
    {
      "@type": "Question",
      "name": "Do you provide SEO consultancy for businesses outside Dubai?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes. While we are based in Dubai, our SEO consultancy services extend to businesses across different regions and industries.\n"
      }
    },
    {
      "@type": "Question",
      "name": "What makes Logic Works different from other SEO consultants?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "We focus on research, clear reporting, and local insight. Every plan is built around business goals and customer behavior. Data guides our work, so no effort is wasted."
      }
    },
    {
      "@type": "Question",
      "name": "Do you provide reports for SEO campaigns?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes, reports are shared often and kept simple. Clients see rankings, traffic, and growth clearly. Every update shows actions, progress, and next steps."
      }
    }
  ]
}
</script>
<!--FAQPage Code Generated by https://saijogeorge.com/json-ld-schema-generator/faq/-->';
include("includes/head.php");
include("includes/header.php");
?>

<style>
    .seo-consultancy {
        background-color: black;
        overflow: hidden;
    }

    .align-items-center {
        align-items: center !important;
        /* margin-top: -105px; */
    }

    .section-marquee .marwuee-row:before {
        height: 120px;
    }
</style>
<main class="seo-consultancy">
    <section class="consultancy-hero-sec section-bg bg-black"
        style="background-image: url('assests/images/branding-dubai/seo-bg.webp'); background-size: cover; background-position: center; background-repeat: no-repeat;">

        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-8 col-md-8">
                    <h1 class="text-white">Drive Business Growth with SEO consultant in Dubai</h1>
                    <p class="text-white">Our SEO consultant in Dubai helps businesses gain higher visibility online.
                        Smart strategies improve rankings, attract local customers, and drive steady growth.</p>
                    <div class="seo-btn specbtn pb-40">
                        <a class="btn bg-theme text-title" href="#0">
                            <span class="link-effect">
                                <span class="effect-1">Live Chat</span>
                                <span class="effect-1">Live Chat</span>
                            </span>
                        </a>
                        <a class="btn bg-theme text-title" id="openPopup" href="#0">
                            <span class="link-effect">
                                <span class="effect-1">Get A Quote</span>
                                <span class="effect-1">Get A Quote</span>
                            </span>
                        </a>
                        <!-- <img src="assests/images/social-media/trustandotherlogo.webp" alt="trust icons" class="trustsec"> -->
                    </div>
                    <div class="">
                        <?php
                        include("includes/image-link.php");
                        ?>
                    </div>
                </div>
                <!-- <div class="col-lg-4 col-md-4">
                        <img src="assests/images/digital-marketing-cosultancy/banner-image.png">
                    </div> -->
            </div>
        </div>
    </section>

    <section class="section-marquee section-bg ">
        <div class="container" style="max-width: 100%; padding: 0px;">
            <div class="row marwuee-row">
                <div class="col" style="padding: 0px;">
                    <div class="marquee">
                        <div class="marquee__row">
                            <div class="marquee__item">
                                <p class="marquee__text">SEO consultancy Agency&nbsp;—&nbsp;SEO consultancy Agency</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/branding-dubai/Star.png"></span>
                            <div class="marquee__item">
                                <p class="marquee__text">SEO consultancy Agency</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/branding-dubai/Star.png"></span>
                            <div class="marquee__item">
                                <p class="marquee__text">SEO consultancy Agency</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/branding-dubai/Star.png"></span>
                        </div>
                        <div aria-hidden="true" class="marquee__row">
                            <div class="marquee__item">
                                <p class="marquee__text">SEO consultancy Agency&nbsp;—&nbsp;SEO consultancy Agency</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/branding-dubai/Star.png"></span>
                            <div class="marquee__item">
                                <p class="marquee__text">SEO consultancy Agency</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/branding-dubai/Star.png"></span>
                            <div class="marquee__item">
                                <p class="marquee__text">SEO consultancy Agency</p>
                            </div>
                            <span class="marquee__separator"><img src="assests/images/branding-dubai/Star.png"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- our seo services-->
    <section class="services-1 animate consultancy-sec mt-60" data-delay="0s"
        style="animation: 0.5s ease-out 0s 1 normal forwards running anim; border-top: 1px solid gray; border-bottom: 1px solid gray;">

        <section class="service-bg mt-30" style="">
            <div class="services__items translateX-parent">
                <div class="line-heading main-serp translateX-right "
                    style="transform: translate3d(157.629px, 0px, 0px);">
                    <h3 class="outline-text">SEO Consultancy Services We Offer</h3>
                    <p class="text-white fs-28 fw-600" style="line-height: 1.2;">Professional consultant SEO solutions
                        designed to improve <br>
                        rankings, traffic, and conversions effectively.</p>

                </div>
                <div class="services-thumb-slider-wrapper">
                    <div
                        class="services-thumb-slider swiper swiper-initialized swiper-vertical swiper-pointer-events swiper-backface-hidden">
                        <div class="swiper-wrapper" id="swiper-wrapper-101022471084cebcb9c" aria-live="polite"
                            style="transition-duration: 0ms; transform: translate3d(0px, 26.6px, 0px);">
                            <div class="swiper-slide swiper-slide-prev" role="group" aria-label="1 / 8"
                                style="height: 26.6px;">
                                <div class="service-thumb__head">
                                    <h2><a>Local SEO Consultancy</a></h2>
                                    <p>Local SEO consultancy helps businesses appear in nearby searches and reach local
                                        customers.
                                    </p>
                                </div>
                            </div>
                            <div class="swiper-slide swiper-slide-active" role="group" aria-label="2 / 8"
                                style="height: 26.6px;">
                                <div class="service-thumb__head">
                                    <h2><a>E-Commerce SEO Consultancy</a></h2>
                                    <p>E-commerce SEO consultancy improves store visibility and strengthens product
                                        performance in search results.</p>
                                </div>
                            </div>
                            <div class="swiper-slide swiper-slide-next" role="group" aria-label="3 / 8"
                                style="height: 26.6px;">
                                <div class="service-thumb__head">
                                    <h2><a>Enterprise SEO Solutions</a></h2>
                                    <p>Enterprise SEO solutions support large organizations that manage many products or
                                        services.</p>
                                </div>
                            </div>
                            <div class="swiper-slide swiper-slide-next" role="group" aria-label="4 / 8"
                                style="height: 26.6px;">
                                <div class="service-thumb__head">
                                    <h2><a>Startup SEO Growth Plans</a></h2>
                                    <p>Startup SEO growth plans focus on giving new businesses the right foundation for
                                        visibility.</p>
                                </div>
                            </div>
                        </div>
                        <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span>


                    </div>
                </div>
                <div
                    class="services-slider swiper swiper-fade swiper-initialized swiper-horizontal swiper-pointer-events swiper-watch-progress swiper-backface-hidden">
                    <div class="swiper-wrapper" id="swiper-wrapper-935aa6bff8fbfe96" aria-live="polite"
                        style="transition-duration: 0ms;">
                        <div class="swiper-slide swiper-slide-prev" role="group" aria-label="1 / 8"
                            style="width: 1349px; opacity: 1; transform: translate3d(0px, 0px, 0px); transition-duration: 0ms;">
                            <div class="service-item twocol-row">
                                <div class="service-item__wrapper twocol-row">
                                    <div class="service-item__img">
                                        <div class="img-wrapper">
                                            <!-- Web Development image -->
                                            <img class="" data-class="lazy-img"
                                                data-src="assests/images/seo-consultancy/seo-service-img-01.webp"
                                                alt="seo-img-webp"
                                                src="assests/images/seo-consultancy/seo-service-img-01.webp">
                                            <h4 class="text-white text-start">Local SEO Consultancy</h4>
                                            <p class="text-white text-start">Local SEO consultancy helps businesses
                                                appear in nearby searches and reach local customers. Accurate listings,
                                                relevant local content, and focused targeting improve presence on maps
                                                and directories. Our experienced consultants provide guidance that
                                                supports steady growth and builds trust with local audiences.
                                            </p>
                                        </div>
                                    </div>
                                    <div class="anchor-wrapper services-anchor">
                                        <a href="javascript:" class="arrow-anchor">
                                            <span>Read More</span>
                                            <div class="img-wrapper">
                                                <svg viewBox="0 0 19 16" class="svg-convert svg-converted"
                                                    src="/assets/svg/anchor-arrow.svg">
                                                    <style type="text/css">
                                                        .st0 {
                                                            fill: #FFFFFF;
                                                        }
                                                    </style>
                                                    <path class="st0" d="M16.2,7.2l0,1.8L1.1,9.3l0-1.8L16.2,7.2z">
                                                    </path>
                                                    <path class="st0"
                                                        d="M11,13.1l-1.1-1.4L14.7,8l-5-3.6l1-1.5l6.8,5.2L11,13.1z">
                                                    </path>
                                                </svg>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide swiper-slide-visible swiper-slide-active" role="group"
                            aria-label="2 / 8"
                            style="width: 1349px; opacity: 1; transform: translate3d(-1349px, 0px, 0px); transition-duration: 0ms;">
                            <div class="service-item twocol-row">
                                <div class="service-item__wrapper twocol-row">
                                    <div class="service-item__img">
                                        <div class="img-wrapper">
                                            <img class="" data-class="lazy-img"
                                                data-src="assests/images/seo-consultancy/seo-service-img-02.webp"
                                                alt="socialmedia-002"
                                                src="assests/images/seo-consultancy/seo-service-img-02.webp">
                                            <h4 class="text-white text-start">E-Commerce SEO Consultancy</h4>
                                            <p class="text-white text-start">E-commerce SEO consultancy improves store
                                                visibility and strengthens product performance in search results.
                                                keyword-rich product pages, and optimized navigation
                                                bring more qualified visitors. Our SEO consultant provides direction
                                                that helps online stores attract buyers, improve revenue, and grow
                                                steadily in competitive digital marketplaces.</p>
                                        </div>
                                    </div>
                                    <div class="anchor-wrapper services-anchor">
                                        <a href="javascript:" class="arrow-anchor">
                                            <span>Read More</span>
                                            <div class="img-wrapper">
                                                <svg viewBox="0 0 19 16" class="svg-convert svg-converted"
                                                    src="/assets/svg/anchor-arrow.svg">
                                                    <style type="text/css">
                                                        .st0 {
                                                            fill: #FFFFFF;
                                                        }
                                                    </style>
                                                    <path class="st0" d="M16.2,7.2l0,1.8L1.1,9.3l0-1.8L16.2,7.2z">
                                                    </path>
                                                    <path class="st0"
                                                        d="M11,13.1l-1.1-1.4L14.7,8l-5-3.6l1-1.5l6.8,5.2L11,13.1z">
                                                    </path>
                                                </svg>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide swiper-slide-next" role="group" aria-label="3 / 8"
                            style="width: 1349px; opacity: 0; transform: translate3d(-2698px, 0px, 0px); transition-duration: 0ms;">
                            <div class="service-item twocol-row">
                                <div class="service-item__wrapper twocol-row">
                                    <div class="service-item__img">
                                        <div class="img-wrapper">
                                            <img class="" data-class="lazy-img"
                                                data-src="assests/images/seo-consultancy/seo-service-img-03.webp"
                                                alt="digital-cons-003"
                                                src="assests/images/seo-consultancy/seo-service-img-03.webp">
                                            <h4 class="text-white text-start">Enterprise SEO Solutions</h4>
                                            <p class="text-white text-start">Enterprise SEO solutions support large
                                                organizations that manage many products or services. We conduct detailed
                                                audits, plan effective keywords, and make technical improvements to
                                                boost rankings in different markets. A skilled SEO consultant helps
                                                maintain authority, keeps strategies consistent, and guides long-term
                                                growth in competitive industries.</p>
                                        </div>
                                    </div>
                                    <div class="anchor-wrapper services-anchor">
                                        <a href="javascript:" class="arrow-anchor">
                                            <span>Read More</span>
                                            <div class="img-wrapper">
                                                <svg viewBox="0 0 19 16" class="svg-convert svg-converted"
                                                    src="/assets/svg/anchor-arrow.svg">
                                                    <style type="text/css">
                                                        .st0 {
                                                            fill: #FFFFFF;
                                                        }
                                                    </style>
                                                    <path class="st0" d="M16.2,7.2l0,1.8L1.1,9.3l0-1.8L16.2,7.2z">
                                                    </path>
                                                    <path class="st0"
                                                        d="M11,13.1l-1.1-1.4L14.7,8l-5-3.6l1-1.5l6.8,5.2L11,13.1z">
                                                    </path>
                                                </svg>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide" role="group" aria-label="4 / 8"
                            style="width: 1349px; opacity: 0; transform: translate3d(-4047px, 0px, 0px); transition-duration: 0ms;">
                            <div class="service-item twocol-row">
                                <div class="service-item__wrapper twocol-row">
                                    <div class="service-item__img">
                                        <div class="img-wrapper">
                                            <img class="" data-class="lazy-img"
                                                data-src="assests/images/seo-consultancy/seo-service-img-04.webp"
                                                alt="digital-mark-005"
                                                src="assests/images/seo-consultancy/seo-service-img-04.webp">
                                            <h4 class="text-white text-start">Startup SEO Growth Plans</h4>
                                            <p class="text-white text-start">Startup SEO growth plans focus on giving
                                                new businesses the right foundation for visibility. Strong keyword
                                                research, content planning, and technical setup ensure early growth and
                                                lasting results. Our expert SEO consultancy service helps startups
                                                compete effectively and gain customer trust during their first stages
                                                online.</p>
                                        </div>
                                    </div>
                                    <div class="anchor-wrapper services-anchor">
                                        <a href="javascript:" class="arrow-anchor">
                                            <span>Read More</span>
                                            <div class="img-wrapper">
                                                <svg viewBox="0 0 19 16" class="svg-convert svg-converted"
                                                    src="/assets/svg/anchor-arrow.svg">
                                                    <style type="text/css">
                                                        .st0 {
                                                            fill: #FFFFFF;
                                                        }
                                                    </style>
                                                    <path class="st0" d="M16.2,7.2l0,1.8L1.1,9.3l0-1.8L16.2,7.2z">
                                                    </path>
                                                    <path class="st0"
                                                        d="M11,13.1l-1.1-1.4L14.7,8l-5-3.6l1-1.5l6.8,5.2L11,13.1z">
                                                    </path>
                                                </svg>
                                            </div>
                                        </a>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span>
                </div>
            </div>
            <!-- <div class="service-btn">
                <div class="live-chat-btns">
                    <a href="#" class="live-chats">Live Chat</a>
                    <a href="#" id="openPopup">Get A Quote</a>
                </div>
            </div> -->
        </section>
    </section>

    <section class="section-bg fifth-consultancy-sec mt-50">
        <?php
        include("components/seo-why-work-us.php");
        ?>
        <div class="container" style="display: block; max-width: 1920px; padding: 0px; margin-top: 90px;">
            <div class="row fifth-consultancy-row">
                <div class="col-lg-12">
                    <h2 class="text-white">OUR PROCESS</h2>
                    <h4 class="text-white">How Our SEO Consultancy Process Works</h4>
                    <!-- <h5 class="text-white">step-by-step process</h5> -->
                    <p class="text-white">Our process ensures every business receives clear direction. A trusted Dubai
                        SEO consultant guides growth through research, strategy, and results.</p>
                </div>
            </div>

            <div class="row align-items-center fifth-inner-row">
                <div class="col-lg-1">
                    <img src="assests/images/digital-marketing-cosultancy/steps.png">
                </div>

                <div class="col-lg-6">
                    <div class="steps-consultancy">
                        <h5 class="text-white">Initial Consultation & Goal Setting</h5>
                        <p class="text-white">We listen carefully, define clear goals, and align our SEO approach.</p>
                    </div>

                    <div class="steps-consultancy">
                        <h5 class="text-white">Research & Strategy Development</h5>
                        <p class="text-white">Our team studies data, competitors, and audience before shaping an
                            effective plan.</p>
                    </div>

                    <div class="steps-consultancy">
                        <h5 class="text-white">Execution & Optimization</h5>
                        <p class="text-white">We apply strategies, refine technical aspects, and improve site visibility
                            consistently.</p>
                    </div>

                    <div class="steps-consultancy">
                        <h5 class="text-white">Tracking Progress & Adjustments
                        </h5>
                        <p class="text-white">Our reports track performance and guide ongoing adjustments for steady
                            results.</p>
                    </div>
                </div>

                <div class="col-lg-5 text-end">
                    <img src="assests/images/branding-dubai/seo-proces.webp">
                </div>
            </div>

        </div>
    </section>
    <section class="six-consultancy-sec pt-b-80"
        style="background-color: #131B1E; margin-top: 100px;  border-top: 1px solid gray; border-bottom: 1px solid gray;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="dubai-all text-white text-center">Success Stories</h2>
                    <p class="text-white dubai-all-para text-center">Success Stories That Show Real Business Growth</p>
                    <div class="unique-tab-container tabs-consultancy">
                        <button class="unique-tab-button active-tab" data-target="UniqueConsultation">
                            <img src="assests/images/branding-dubai/icon-1.webp" alt="seo-icon-001"
                                style="height: 40px; width: 40px;">
                            E-commerce Brand
                        </button>

                        <button class="unique-tab-button" data-target="UniqueConcept"><img
                                src="assests/images/branding-dubai/icon-2.webp" alt="seo-icon-002">Real Estate
                            Agency</button>
                        <button class="unique-tab-button" data-target="UniqueRevisions"><img
                                src="assests/images/branding-dubai/icon-3.webp" alt="seo-icon-003">SaaS Company</button>
                        <button class="unique-tab-button" data-target="UniqueDelivery"><img
                                src="assests/images/branding-dubai/icon-4.webp" alt="seo-icon-004">Travel
                            Agency</button>
                    </div>

                    <div class="tab-delivery">
                        <div class="unique-tab-container">
                            <div id="UniqueConsultation" class="unique-tab-content" style="display: block;">
                                <div class="row align-items-center">
                                    <div class="col-lg-12">
                                        <div class="consultancy-tab-content">
                                            <div class="row align-items-center">
                                                <div class="col-lg-7">
                                                    <img src="assests/images/seo-consultancy/story-img-1.webp"
                                                        alt="seo-success-001">
                                                </div>
                                                <div class="col-lg-5">
                                                    <div class="tab-data-consultancy">
                                                        <h2 class="text-white">E-commerce Brand</h2>
                                                        <p class="text-white same-all-para">An online retail store faced
                                                            low visibility and slow sales. We improved product pages,
                                                            fixed technical issues, and grew organic traffic. The store
                                                            achieved higher search rankings and stronger revenue within
                                                            months.</p>
                                                        <p class="text-white">Our guidance as an experienced SEO
                                                            consultant helped the business reach customers more
                                                            effectively and create a steady stream of orders.</p>
                                                        <a href="#0">EXPLORE IT</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id="UniqueConcept" class="unique-tab-content">
                                <div class="row align-items-center">
                                    <div class="col-lg-12">
                                        <div class="consultancy-tab-content">
                                            <div class="row align-items-center">
                                                <div class="col-lg-7">
                                                    <img src="assests/images/seo-consultancy/story-img-2.webp"
                                                        alt="seo-success-002">
                                                </div>
                                                <div class="col-lg-5">
                                                    <div class="tab-data-consultancy">
                                                        <h2 class="text-white">Real Estate Agency</h2>
                                                        <p class="text-white same-all-para">A real estate agency needed
                                                            more qualified leads. We optimized property listings,
                                                            improved local SEO, and built better search presence. The
                                                            agency began receiving more calls and form submissions from
                                                            people in their target areas.</p>
                                                        <p class="text-white">Our consultants provided strategies that
                                                            supported consistent growth in both visibility and customer
                                                            inquiries over time.</p>
                                                        <a href="#0">EXPLORE IT</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id="UniqueRevisions" class="unique-tab-content">
                                <div class="row align-items-center">
                                    <div class="col-lg-12">
                                        <div class="consultancy-tab-content">
                                            <div class="row align-items-center">
                                                <div class="col-lg-7">
                                                    <img src="assests/images/seo-consultancy/story-img-3.webp"
                                                        alt="seo-success-003">
                                                </div>
                                                <div class="col-lg-5">
                                                    <div class="tab-data-consultancy">
                                                        <h2 class="text-white">SaaS Company</h2>
                                                        <p class="text-white same-all-para">A SaaS business was
                                                            struggling to get any foot in the door in a crowded market.
                                                            We streamlined their website structure, keyword targeting
                                                            and produced targeted content. Traffic was up dramatically
                                                            and so were demo sign-ups and subscription conversions</p>
                                                        <p class="text-white">Using our SEO consultancy we positioned
                                                            them strongly in the market with their niche and kept growth
                                                            measurable and sustainable for long-term success</p>
                                                        <a href="#0">EXPLORE IT</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id="UniqueDelivery" class="unique-tab-content">
                                <div class="row align-items-center">
                                    <div class="col-lg-12">
                                        <div class="consultancy-tab-content">
                                            <div class="row align-items-center">
                                                <div class="col-lg-7">
                                                    <img src="assests/images/seo-consultancy/story-img-4.webp"
                                                        alt="seo-success-004">
                                                </div>
                                                <div class="col-lg-5">
                                                    <div class="tab-data-consultancy">
                                                        <h2 class="text-white">Travel Agenc</h2>
                                                        <p class="text-white same-all-para">A travel agency required
                                                            stronger online reach to attract seasonal customers. We
                                                            optimized destination pages, built local visibility, and
                                                            improved technical performance. The agency experienced
                                                            higher traffic during peak seasons and steady inquiries
                                                            year-round.</p>
                                                        <p class="text-white">Our team guided them with strategies that
                                                            supported bookings and improved brand visibility. These
                                                            efforts created growth aligned with their business goals.
                                                        </p>
                                                        <a href="#0">EXPLORE IT</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container row align-items-center transform-row cta-sec pt-20 pb-20">
        <div class="col-lg-4">
            <img src="assests/images/marketing/banda.webp" alt="seo-gta-con" class="gta">
        </div>
        <div class="col-lg-8">
            <h2 class="text-white same-all text-end">We have transformed 8000+ business with our Development
                Expertise</h2>
            <div class="digital-two-btn">
                 <a href="tel:+971529502258">Call Now</a>
                <a href="#" id="openPopup">Start Live Chat</a>
            </div>
        </div>
    </div>

    <!-- Ask any Q -->
    <section class="faq-home section-bg mt-50">
        <div class="container">
            <div class="row justify-content-space-between">
                <div class="col">
                    <h2 class="text-white"><span>Frequently </span>Asked Questions</h2>
                    <div class="faqss">
                        <div class="quwstion">
                            <button class="accordions">How long does it take to see results from SEO
                                consultancy?</button>
                            <div class="panel">
                                <p>SEO results vary based on competition, website condition, and goals. Many clients
                                    begin noticing improvements in visibility within three to six months.</p>
                            </div>
                        </div>

                        <div class="quwstion">
                            <button class="accordions">Can you work alongside our in-house marketing team?</button>
                            <div class="panel">
                                <p> Yes. We often support in-house teams by providing strategy, technical guidance, and
                                    reporting that align with their ongoing efforts.
                                </p>
                            </div>
                        </div>

                        <div class="quwstion">
                            <button class="accordions">Do you provide SEO consultancy for businesses outside
                                Dubai?</button>
                            <div class="panel">
                                <p>Yes. While we are based in Dubai, our SEO consultancy services extend to businesses
                                    across different regions and industries.</p>
                            </div>
                        </div>

                        <div class="quwstion">
                            <button class="accordions">What makes Logic Works different from other SEO
                                consultants?</button>
                            <div class="panel">
                                <p>We focus on clear communication, measurable results, and strategies built around each
                                    client’s business goals rather than one-size-fits-all solutions.</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="animated-row section new-york-hire constructionpage_custom_faqs_section pt-b-80 section-bg"
        id="hireobserverID">
        <div class="bg-white-heading-custom">
            <div class="container">
                <div class="row white-bg-heading-custom-row">
                    <div class="col-md-12">
                        <h2 class="section-title">Questionnaire<span>Section</span></h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <nav id="sidenavcustomnavccnav" class="sidenavcustomnavccnav">
                        <ul class="faq_section">
                            <li><a href="#section-1" class="hire-tabs current" id="currentIDRRRRRRR">How Does Logic
                                    Works Approach Social Media Marketing?</a></li>
                            <li><a href="#section-2" class="hire-tabs">What Makes Logic Works Unique in Digital
                                    Strategy?</a></li>
                            <li><a href="#section-3" class="hire-tabs">How Does Logic Works Track Campaign
                                    Performance?</a></li>
                            <li><a href="#section-4" class="hire-tabs">What Results Can Clients Expect From Logic
                                    Works?</a></li>
                            <li><a href="#section-5" class="hire-tabs">How Does Logic Works Support Long-Term Business
                                    Growth?</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-6 col-md-6 col-stick">
                    <main>
                        <section class="sec-info" id="section-1">
                            <h2>How Does Logic Works Approach Social Media Marketing?</h2>
                            <ul>
                                <p>Our team focuses on building strategies that match business goals and customer
                                    interests. We study your audience, track their behavior, and create campaigns that
                                    drive real engagement. Content planning, ad management, and consistent reporting
                                    form the base of our approach. A Dubai SEO consultant can also support social media
                                    by connecting campaigns with search visibility, creating stronger overall results.
                                    Our goal is measurable growth. We focus on building trust between brands and
                                    customers. Every step keeps campaigns effective and sustainable.</p>
                            </ul>
                        </section>
                        <section class="sec-info" id="section-2">
                            <h2>What Makes Logic Works Unique in Digital Strategy?</h2>
                            <ul>
                                <p>Logic Works is different because we focus on clarity, results, and transparency.
                                    Every business has different needs, and we adjust our approach to fit them. Our
                                    strategies use technical skills, creative thinking, and performance tracking to
                                    deliver lasting results. Clients get a partner who listens and makes changes when
                                    needed. A skilled consultant seo within our team ensures search efforts are
                                    integrated with digital campaigns. Clear reporting, dedicated support, and practical
                                    recommendations help our clients grow. We measure success by how well our strategies
                                    impact real business goals rather than vanity numbers</p>
                            </ul>
                        </section>
                        <section class="sec-info" id="section-3">
                            <h2>How Does Logic Works Track Campaign Performance?</h2>
                            <ul>
                                <p>Performance tracking depends on clear data and honest reporting. We check rankings,
                                    website traffic, and conversions to see progress. Reports are straightforward,
                                    showing what works well and what needs changes. This way, clients feel confident
                                    about every step. Our process includes short-term and long-term tracking so growth
                                    continues over time. Regular meetings keep clients updated and involved in the
                                    process. An experienced SEO consultant provides guidance, helping businesses make
                                    clear and confident choices. Tracking performance is more than looking at numbers;
                                    it shows real results that support growth and build long-term trust.</p>
                            </ul>
                        </section>
                        <section class="sec-info" id="section-4">
                            <h2>What Results Can Clients Expect From Logic Works?</h2>
                            <ul>
                                <p>Clients can expect results that align with their business objectives. Our consultancy
                                    focuses on improved visibility, higher traffic, and stronger conversions. We avoid
                                    empty promises and instead provide steady progress that can be measured. Each
                                    campaign is built around research and execution designed to make a difference.
                                    Businesses often notice stronger search rankings and a rise in quality leads.
                                    Guidance from an experienced seo consultant in dubai ensures strategies stay
                                    relevant and effective. We believe results must always connect back to growth and
                                    customer satisfaction. That’s the standard we keep for every project we manage.</p>
                            </ul>
                        </section>
                        <section class="sec-info" id="section-5">
                            <h2>How Does Logic Works Support Long-Term Business Growth?</h2>
                            <ul>
                                <p>Long-term growth comes from steady planning, regular updates, and keeping up with
                                    market changes. Our consultancy builds a solid foundation that helps results last
                                    over time. We keep campaigns fresh, websites well-optimized, and content useful for
                                    your audience. Ongoing support includes clear reports that show progress and
                                    improvements. A skilled SEO consultant guides these steps so businesses stay strong
                                    in a changing market. Growth is not only about quick numbers but also about building
                                    stability for the future. Our intent is to stand alongside our clients and help them
                                    move forward step by step.</p>
                            </ul>
                        </section>
                    </main>
                </div>
            </div>
        </div>
    </section>
    <?php
    include("includes/clint-review.php");
    ?>
</main>
<?php
include("includes/footer.php");
?>